#docker-compose version 정의
version: "3.9"
# docker 서비스 정의
services:
  mydb:
		# 도커 이미지 선택
    image: mysql:8.0
		# 서비스 컨테이너 이름 지정
    container_name: mysql_app
		# 컨테이너 볼륨 지정
    volumes: 
      -mydb_data:/var/lib/mysql
		# 수동 제어를 제외한 컨테이너 종료 시 자동 재시작
    restart: always
		# 포트 포워딩(호스트 포트와 컨테이너 포트 바인드)
    ports:
      - "3306:3306"
		# 네트워크 지정
    networks:
      - backend-net
		# 서비스가 사용할 환경 변수를 지정
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    myweb:
			# myweb 서비스가 실행되기 전에 mydb 서비스를 먼저 실행하는 의존성 설정
      depends_on:
        - mydb
      image: wordpress:5.7
      container_name: wordpress_app
      ports:
        - "8888:80"
			# backend-net으로 mydb 서비스와 동일 네트워크로 지정하고,
			# 외부 연결을 위한 네트워크를 위해 frontend-net 지정
			# docker network connect 명령으로 네트워크를 추가하는 것과 같음
      networks:
        - backend-net
        - frontend-net
      volumes:
        - myweb_data:/var/www/html
        - ${PWD}/myweb-log:/var/log \
      restart: always
      environment:
        WORDPRESS_DB_HOST: mydb:3306
        WORDPRESS_DB_USER: wpuser
        WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        WORDPRESS_DB_NAME: wpdb

networks:
  frontend-net: {}
  backend-net: {}

volumes:
  mydb_data: {}
  myweb_data: {}